
export const traducirHabitat = (habitat) =>{
    if(habitat === 'grassland') return 'Pradera'
    if(habitat === 'mountain') return 'Montaña'
    if(habitat === 'rare') return 'Raro'
    if(habitat === 'rough-terrain') return 'Terreno Dificil'
    if(habitat === 'sea') return 'Mar'
    if(habitat === 'urban') return 'Urbano'
    if(habitat === 'waters-edge') return 'Al borde del agua'
    if(habitat === 'cave') return 'Cueva'
    if(habitat === 'forest') return 'Bosque'
}
export const traducirTipo = (tipo) =>{
    if(tipo === 'normal') return 'Normal'
    if(tipo === 'fighting') return 'Lucha'
    if(tipo === 'grass') return 'Césped'
    if(tipo === 'rock') return 'Roca'
    if(tipo === 'electric') return 'Electrico'
    if(tipo === 'psychic') return 'Psíquico'
    if(tipo === 'flying') return 'Volador'
    if(tipo === 'bug') return 'Bicho'
    if(tipo === 'ice') return 'Hielo'
    if(tipo === 'ghost') return 'Fantasma'
    if(tipo === 'dragon') return 'Dragon'
    if(tipo === 'dark') return 'Oscuro'
    if(tipo === 'steel') return 'Acero'
    if(tipo === 'poison') return 'Veneno'
    if(tipo === 'fire') return 'Fuego'
    if(tipo === 'fairy') return 'Hada'
    if(tipo === 'water') return 'Agua'
    if(tipo === 'unknown') return 'Desconocido'
    if(tipo === 'ground') return 'Suelo'
    if(tipo === 'shadow') return 'Sombra'
}